Added Debian salsa also into Tracker
aquasecurity/vuln-list-update pull request #92
Opened 2021-06-21 18:09 UTC by tonaim

1. Capture security Advisory DSL and DLA
2. Relation between security advisory and CVE
3. Support EOL version in trivy. Currently Trivy supports CVEs which have fixed versions. But we should support open CVEs also.
4. Capture vendor severity
5. Capture will not fix CVEs

2021-06-22 12:09 UTC, knqyf263 reviewed
Please write tests

2021-06-22 12:09 UTC, knqyf263 commented on debian/salsa/debian.go
> +func (ctx *DebianSalsa) parseCVEs() error {
Why do we need to parse CVE? For EOL version? Are DLA/DSA not enough? Can we obtain metadata such as severity from security tracker?
https://security-tracker.debian.org/tracker/data/json

And this method is not DRY-ed. Please refactor it.

2021-06-23 18:29 UTC, tonaim commented on debian/salsa/debian.go
> +func (ctx *DebianSalsa) parseCVEs() error {
yes we would like to parse CVEs also, because we can find open CVEs for EOL versions here. Example CVE-2020-15395 is not fixed in jessie release and we can get that information here. 
![image](https://user-images.githubusercontent.com/65420264/123149422-e0f43280-d47e-11eb-97b4-266813b8a076.png)

2021-07-19 07:09 UTC, knqyf263 requested changes

2021-07-19 07:09 UTC, knqyf263 commented on debian/salsa/debian_test.go
> +func TestDebianSalsa_getReleases(t *testing.T) {
Please write tests only for Update().

2021-07-19 07:09 UTC, knqyf263 commented on debian/salsa/debian_test.go
> +package salsa
```suggestion
package salsa_test
```

2021-07-19 07:09 UTC, knqyf263 commented on debian/salsa/debian_test.go
> +			assert.NoError(t, err, "failed to create temp dir")
Please refer to other tests.

2021-07-19 07:09 UTC, knqyf263 commented on debian/salsa/debian_test.go
> +		{name: "All functions", fields: releaseFields, wantErr: false, wantOss: ossData, wantCVEtoDSA: wantCVEtoDSAData},
Keep a single case small and should add more cases.

2021-07-19 07:09 UTC, knqyf263 commented on debian/salsa/debian_test.go
> +				want, err := ioutil.ReadFile(golden)
ioutil is deprecated

2021-07-19 07:09 UTC, knqyf263 commented on debian/salsa/debian_test.go
> +		VulnListDir:    "testdata/got",
Should use t.TempDir()

2021-07-19 07:09 UTC, knqyf263 commented on debian/salsa/debian.go
> +	gc := git.Config{}
Doesn't tarball work?
https://salsa.debian.org/security-tracker-team/security-tracker/-/archive/master/security-tracker-master.tar.gz

2021-12-12 06:09 UTC, knqyf263 commented
In favor of #95

2021-12-12 06:09 UTC, closed without merging